# Generated by Django 5.1.7 on 2025-06-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Lider', 'LIDER'), ('Usuario', 'USUARIO')], default='Usuario', verbose_name='Cargo'),
        ),
    ]
