# Generated by Django 5.1.7 on 2025-06-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Lider', 'LIDER'), ('Tester', 'TESTER')], default='Usuario', verbose_name='Cargo'),
        ),
    ]
