# Generated by Django 5.1.7 on 2025-06-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipo',
            field=models.CharField(choices=[('Roku', 'Roku'), ('STV(TATA)', 'STV(TATA)'), ('STB', 'STB'), ('WEB', 'WEB'), ('IOS', 'IOS')], default='STB', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('Lider', 'LIDER'), ('Tester', 'TESTER')], default='Tester', verbose_name='Cargo'),
        ),
    ]
