# Generated by Django 5.1.7 on 2025-06-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_equipo_alter_user_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='equipo',
            field=models.CharField(blank=True, choices=[('Roku', 'Roku'), ('STV(TATA)', 'STV(TATA)'), ('STB', 'STB'), ('WEB', 'WEB'), ('IOS', 'IOS')], null=True, verbose_name='Equipo'),
        ),
    ]
