# Generated by Django 5.1.7 on 2025-06-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='equipo',
            field=models.CharField(blank=True, choices=[('Claro TV STB - IPTV - Roku - TATA', 'Claro TV STB - IPTV - Roku - TATA'), ('STV (LG,Samsung,ADR), Kepler-FireTV, STV2(Hisense,Netrange)', 'STV (LG,Samsung,ADR), Kepler-FireTV, STV2(Hisense,Netrange)'), ('IPTV  AOSP', 'IPTV  AOSP'), ('WIN - WEB - Fire TV', 'WIN - WEB - Fire TV'), ('IOS - TvOS', 'IOS - TvOS'), ('Android', 'Android'), ('Smart TV AAF', 'Smart TV AAF')], null=True, verbose_name='Equipo'),
        ),
    ]
