version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: qc_admin
      POSTGRES_PASSWORD: qc_admin_pass
      POSTGRES_DB: qc_matrix
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    ports:
      - "8080:8000"
    volumes:
      - ./:/app
      - staticfiles-volume:/app/staticfiles
    environment:
      - DEBUG=1
      - POSTGRES_DB=qc_matrix
      - POSTGRES_USER=qc_admin
      - POSTGRES_PASSWORD=qc_admin_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - JIRA_EMAIL=s_tamezaa@globalhitss.com
      - JIRA_API_TOKEN=ATATT3xFfGF0XqHq8pFnTA7X5KnVtKy9twdH_h0ljMzcnNGLdB3bo_LMX9_MR_AkPJMLNl7ctkFESPw5nHLVIEYILIxhLrukB-OdxO8eU4BtBCOlBdkRTu8GR1PCGR48LBdHZzlWvMNq7_z0HTWjUdOWWyoKSHIys5UEBNQx3SduhKFbyCXWYbI=5B754F4D
    depends_on:
      - db
    command: > 
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        if [ -f /app/initialdata.json ]; then
            python manage.py loaddata /app/initialdata.json;
        fi &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data:
  staticfiles-volume:

