version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_data:/vol/static
      - media_data:/vol/web/media
      - sockets:/tmp/sockets
        # Montar la SQLite directamente
    environment:
      - SECRET_KEY=qcsecretkey
      - ALLOWED_HOSTS=localhost,127.0.0.1,200.57.172.7,200.57.172.8
      - DEBUG=False
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=unacontraseñasegura
    user: "1000:1000"
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - static_data:/vol/static:ro
      - media_data:/vol/web/media:ro
      - sockets:/tmp/sockets
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  static_data:
  media_data:
  sockets: