version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    
    # NO montar volúmenes que sobrescriban permisos
    volumes:
      - db_data:/app/db
    
    environment:
      - DEBUG=1
      - DOCKER_ENV=true
      - PYTHONUNBUFFERED=1

volumes:
  db_data: