version: '3.9'

networks:
  qc_network:
    driver: bridge

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: qc_admin
      POSTGRES_PASSWORD: qc_admin_pass
      POSTGRES_DB: qc_matrix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - qc_network

  app:
    build:
      context: .
    volumes:
      - ./:/app
      - staticfiles-volume:/app/staticfiles
    environment:
      - DEBUG=0
      - POSTGRES_DB=qc_matrix
      - POSTGRES_USER=qc_admin
      - POSTGRES_PASSWORD=qc_admin_pass
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        if [ -f /app/initialdata.json ]; then python manage.py loaddata /app/initialdata.json; fi &&
        uwsgi --socket :8000 --master --module main_website.wsgi --enable-threads
      "
    networks:
      - qc_network

  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    volumes:
      - staticfiles-volume:/vol/static
    depends_on:
      - app
    networks:
      - qc_network

volumes:
  postgres_data:
  staticfiles-volume:
