# Generated by Django 5.1.7 on 2025-06-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alcances_utilizados', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperMatriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasoDePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(max_length=5)),
                ('fase', models.CharField(max_length=50)),
                ('caso_de_prueba', models.TextField()),
                ('estado', models.CharField(default='Por ejecutar', max_length=50)),
                ('criticidad', models.CharField(choices=[('Bloqueante', 'Bloqueante'), ('Crítico', 'Crítico')], max_length=15)),
                ('nota', models.TextField(blank=True, null=True)),
                ('tester', models.TextField(blank=True, null=True)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='matrix.matriz')),
            ],
        ),
        migrations.AddField(
            model_name='matriz',
            name='super_matriz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrices', to='matrix.supermatriz'),
        ),
        migrations.CreateModel(
            name='DetallesValidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro_RN', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario_RN', models.TextField(blank=True, null=True)),
                ('super_matriz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_validate', to='matrix.supermatriz')),
            ],
        ),
        migrations.CreateModel(
            name='TicketPorLevantar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(max_length=100)),
                ('ticket_SCT', models.CharField(blank=True, max_length=10, null=True)),
                ('BRF', models.CharField(blank=True, max_length=30, null=True)),
                ('Region', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=70)),
                ('prioridad', models.CharField(max_length=50)),
                ('nota', models.TextField(max_length=70)),
                ('url', models.URLField(blank=True, null=True)),
                ('super_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_por_levantar', to='matrix.supermatriz')),
            ],
        ),
        migrations.CreateModel(
            name='Validate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validates', to='matrix.matriz')),
                ('super_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validates', to='matrix.supermatriz')),
            ],
        ),
    ]
