# Generated by Django 5.1.7 on 2025-06-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermatriz',
            name='equipo',
            field=models.CharField(choices=[('Claro TV STB - IPTV - Roku - TATA', 'Claro TV STB - IPTV - Roku - TATA'), ('STV (LG,Samsung,ADR), Kepler-FireTV, STV2(Hisense,Netrange)', 'STV (LG,Samsung,ADR), Kepler-FireTV, STV2(Hisense,Netrange)'), ('IPTV AOSP', 'IPTV AOSP'), ('WIN - WEB - Fire TV', 'WIN - WEB - Fire TV'), ('IOS - TvOS', 'IOS - TvOS'), ('Android', 'Android'), ('Smart TV AAF', 'Smart TV AAF')], default='STB', verbose_name='Equipo'),
        ),
    ]
