# Generated by Django 5.1.7 on 2025-06-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermatriz',
            name='equipo',
            field=models.CharField(choices=[('Roku', 'Roku'), ('STV(TATA)', 'STV(TATA)'), ('STB', 'STB'), ('WEB', 'WEB'), ('IOS', 'IOS')], default='STB', verbose_name='Equipo'),
        ),
    ]
