# Generated by Django 5.1.7 on 2025-06-30 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_equipo_user_equipo_nuevo'),
        ('matrix', '0002_alter_supermatriz_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermatriz',
            name='equipo_nuevo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supermatrices', to='accounts.equipo'),
        ),
        migrations.AlterField(
            model_name='supermatriz',
            name='equipo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Equipo'),
        ),
    ]
