# Generated by Django 5.1.7 on 2025-06-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0002_supermatriz_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermatriz',
            name='descripcion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supermatriz',
            name='nombre',
            field=models.CharField(max_length=75),
        ),
    ]
