# Generated by Django 5.1.7 on 2025-06-30 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_equipo_user_equipo_nuevo'),
        ('matrix', '0003_supermatriz_equipo_nuevo_alter_supermatriz_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=75)),
                ('matriz_base', models.CharField(max_length=75)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='accounts.equipo')),
            ],
        ),
    ]
