# Generated by Django 5.1.7 on 2025-06-30 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_dispositivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='dispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrices', to='matrix.dispositivo'),
        ),
    ]
