# Generated by Django 5.1.7 on 2025-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0005_matriz_dispositivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriz',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
