# Generated by Django 5.1.7 on 2025-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0006_alter_matriz_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesvalidate',
            name='filtro_RN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
