# Generated by Django 5.1.7 on 2025-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0007_alter_detallesvalidate_filtro_rn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casodeprueba',
            name='nota',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
