# Generated by Django 5.2.5 on 2025-08-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0008_alter_casodeprueba_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermatriz',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Tentativa'),
        ),
    ]
