# Generated by Django 5.2.5 on 2025-09-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0010_ticketporlevantar_tester_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='tester',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
