# Generated by Django 5.2.5 on 2025-09-23 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0011_alter_ticketporlevantar_tester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='testers',
            field=models.ManyToManyField(blank=True, related_name='matrices_asignadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
