# Generated by Django 5.2.5 on 2025-10-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0013_casodeprueba_pais_casodeprueba_tester_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermatriz',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
