# Generated by Django 5.2.5 on 2025-10-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0013_casodeprueba_pais_casodeprueba_tester_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermatriz',
            name='archivado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
