# Generated by Django 5.2.5 on 2025-10-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0014_alter_supermatriz_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='operativo',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Operativo'),
        ),
    ]
