# Generated by Django 5.2.5 on 2025-10-02 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0014_supermatriz_archivado'),
        ('matrix', '0015_dispositivo_operativo'),
    ]

    operations = [
    ]
