# Generated by Django 5.2.5 on 2025-10-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0016_merge_20251001_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketporlevantar',
            name='prioridad',
            field=models.CharField(choices=[('bloqueante', 'Bloqueante'), ('critico', 'Critico')], max_length=50),
        ),
    ]
