# Generated by Django 5.2.7 on 2025-10-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0017_alter_ticketporlevantar_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casodeprueba',
            name='nota',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
