# Generated by Django 5.2.7 on 2025-10-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0018_alter_casodeprueba_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeprueba',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='casodeprueba',
            name='pasos',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='casodeprueba',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
