# Generated by Django 5.2.7 on 2025-10-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0019_casodeprueba_etiqueta_casodeprueba_pasos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeprueba',
            name='mdp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casodeprueba',
            name='monto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casodeprueba',
            name='navegador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
