# Generated by Django 5.2.8 on 2025-12-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0020_casodeprueba_mdp_casodeprueba_monto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casodeprueba',
            name='mdp',
        ),
        migrations.RemoveField(
            model_name='casodeprueba',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='casodeprueba',
            name='navegador',
        ),
    ]
