# Generated by Django 5.2.8 on 2026-01-02 18:35

import django.core.files.storage
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0021_remove_casodeprueba_mdp_remove_casodeprueba_monto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositivo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/excel', location='/home/lgabino/Documentos/qc_matrix_generator/media/excel'), upload_to='dispositivos/', verbose_name='Archivo Excel'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='matriz_base',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
