# Generated by Django 5.2.7 on 2026-02-10 17:26

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0022_alter_dispositivo_options_dispositivo_archivo_excel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/excel/', location='/Users/jesusalberca/Desktop/qc_matrix_generator/media/excel'), upload_to='', verbose_name='Archivo Excel'),
        ),
        migrations.CreateModel(
            name='FeatureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_feature', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/features/', location='/Users/jesusalberca/Desktop/qc_matrix_generator/media/features'), upload_to='', verbose_name='Archivo Gherkin (.feature)')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_relativa', models.CharField(max_length=500)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_files', to='matrix.dispositivo')),
                ('super_matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_files', to='matrix.supermatriz')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('super_matriz', 'ruta_relativa')},
            },
        ),
        migrations.CreateModel(
            name='FeatureScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_id', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=500)),
                ('linea', models.IntegerField()),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('por_ejecutar', 'Por ejecutar'), ('funciona', 'Funciona'), ('falla_nueva', 'Falla nueva'), ('falla_persistente', 'Falla persistente'), ('bloqueado', 'Bloqueado'), ('n_a', 'N/A')], default='por_ejecutar', max_length=30)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('sincronizado_en', models.DateTimeField(auto_now=True)),
                ('feature_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='matrix.featurefile')),
            ],
            options={
                'ordering': ['linea'],
                'unique_together': {('feature_file', 'stable_id')},
            },
        ),
    ]
