# Generated by Django 5.2.8 on 2026-04-13 17:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0022_alter_dispositivo_options_dispositivo_archivo_excel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeprueba',
            name='criterio_aceptacion',
            field=models.TextField(blank=True, null=True, verbose_name='Criterio de aceptación'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='archivo_excel',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/excel/', location='/home/lgabino/Documentos/qc_matrix_generator/media/excel'), upload_to='', verbose_name='Archivo Excel'),
        ),
    ]
