# Generated by Django 5.2.7 on 2026-02-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0023_alter_dispositivo_archivo_excel_featurefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casodeprueba',
            name='scenario_stable_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='featurefile',
            name='matriz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_file', to='matrix.matriz'),
        ),
    ]
