# Generated by Django 5.2.7 on 2026-02-13 17:10

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


def drop_old_unique_if_exists(apps, schema_editor):
    """Elimina el unique_together (super_matriz, ruta_relativa) si existe (solo PostgreSQL)."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'matrix_featurefile'::regclass
              AND contype = 'u'
              AND pg_get_constraintdef(oid) LIKE '%%super_matriz_id%%'
              AND pg_get_constraintdef(oid) LIKE '%%ruta_relativa%%'
        """)
        rows = cursor.fetchall()
        for (conname,) in rows:
            safe_name = conname.replace('"', '""')
            cursor.execute(f'ALTER TABLE matrix_featurefile DROP CONSTRAINT IF EXISTS "{safe_name}"')


def drop_matriz_id_index_if_exists(apps, schema_editor):
    """Elimina índice y/o restricción UNIQUE en matriz_id (del OneToOne previo) para que AlterField a FK funcione (solo PostgreSQL)."""
    if schema_editor.connection.vendor != 'postgresql':
        return
    with schema_editor.connection.cursor() as cursor:
        # Quitar restricción UNIQUE en matriz_id (OneToOne la crea)
        cursor.execute("""
            SELECT conname FROM pg_constraint
            WHERE conrelid = 'matrix_featurefile'::regclass
              AND contype = 'u'
              AND pg_get_constraintdef(oid) LIKE '%%matriz_id%%'
        """)
        for (conname,) in cursor.fetchall():
            safe = conname.replace('"', '""')
            cursor.execute(f'ALTER TABLE matrix_featurefile DROP CONSTRAINT IF EXISTS "{safe}"')
        # Quitar índice con nombre tipo matrix_featurefile_matriz_id_*
        cursor.execute("""
            SELECT indexname FROM pg_indexes
            WHERE tablename = 'matrix_featurefile'
              AND indexname LIKE 'matrix_featurefile_matriz_id%%'
        """)
        for (indexname,) in cursor.fetchall():
            safe = indexname.replace('"', '""')
            cursor.execute(f'DROP INDEX IF EXISTS "{safe}"')


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0025_featurefile_archivo_csv_casodeprueba_datos_examples'),
    ]

    operations = [
        migrations.RunPython(drop_old_unique_if_exists, migrations.RunPython.noop),
        migrations.RunPython(drop_matriz_id_index_if_exists, migrations.RunPython.noop),
        # Marcar en el estado que unique_together ya no es (super_matriz, ruta_relativa), sin tocar la BD.
        # Así AlterUniqueTogether más abajo solo creará (matriz, ruta_relativa) y no intentará borrar uno inexistente.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='featurefile',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='featurefile',
            name='archivo_csv',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/features/', location='/Users/jesusalberca/Desktop/qc_matrix_generator/media/features'), upload_to='csv/', verbose_name='CSV de Examples (opcional)'),
        ),
        migrations.AlterField(
            model_name='featurefile',
            name='matriz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_files', to='matrix.matriz'),
        ),
        migrations.AlterUniqueTogether(
            name='featurefile',
            unique_together={('matriz', 'ruta_relativa')},
        ),
    ]
