map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream django_http {
    server app:8000;  # Aquí corre tu Django con Gunicorn o runserver normal HTTP
}

upstream django_ws {
    server app:8180;  # Daphne solo WS
}

server {
    listen 80;
    server_name _;

    location /static/ {
        alias /vol/static/;
    }

    location /media/ {
        alias /vol/media/;
    }

    # Proxy WS a Daphne 8180
    location /ws/ {
        proxy_pass http://django_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_read_timeout 3600;
        proxy_send_timeout 3600;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy HTTP normal a Gunicorn o runserver en 8000
    location / {
        proxy_pass http://django_http;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
