server {
    listen 80;
    server_name 200.57.172.7;

    location /static/ {
        alias /vol/static/;
        expires 1d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /vol/media/;
    }

    # HTTP normal a Gunicorn
    location / {
        proxy_pass http://django_http;
        include proxy_params;
        proxy_redirect off;
    }

    # WebSocket (prefijo /ws/) a Daphne
    location /ws/ {
        proxy_pass http://django_ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}
